{% set name = "speclite" %}
{% set version = "0.8" %}
{% set sha256 = "b1bc7cbcf4af7584dd81f764f701bb5e94c6998d0ebb9d8404ddca53eff091ea" %}

package:
  version: '{{ version }}'
  name: '{{ name|lower }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  fn: '{{ name }}-{{ version }}.tar.gz'
  sha256: {{sha256}}
  
build:
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record record.txt

requirements:

  build:
    - python
    - setuptools
    - astropy

  run:
    - python
    - numpy
    - scipy
    - astropy
    - pyyaml

test:

  imports:
    - speclite
    
  commands:
    # Execute the full test suite
    
    - cd ${PREFIX}/lib/python*/site-packages/speclite/tests ; py.test -vv  # [not win]
  
  requires:
    - pytest
    - pyyaml
    - matplotlib

about:
  home: http://speclite.readthedocs.io/en/latest/overview.html
  license: BSD-3-Clause
  license_family: BSD
  summary: 'This package provides a set of lightweight utilities for working with spectroscopic data in astronomy. Based on the astropy affiliated package template.'
  license_file: licenses/LICENSE.rst
  dev_url: https://github.com/dkirkby/speclite
  doc_url: http://speclite.readthedocs.io/en/latest/overview.html
  
extra:
  recipe-maintainers:
    - giacomov
    - dkirkby
