{% set name = "speclite" %}
{% set version = "0.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/speclite-{{ version }}.tar.gz
  sha256: 55ae62c72b183eee13598c36f83f3c146ae1c7624dee3ed40581cb956b59fd39

build:
  number: 0
  noarch: python
  entry_points:
    - speclite_benchmark = speclite.benchmark:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - astropy
  run:
    - python >=3.6
    - numpy
    - scipy
    - astropy
    - pyyaml

test:
  imports:
    - speclite
    - speclite.extern
  commands:
    - pip check
    - speclite_benchmark --help
  requires:
    - pip

  commands:
    # Execute the full test suite
    - cd ${PREFIX}/lib/python*/site-packages/speclite/tests ; pytest -vv  # [not win]
  requires:
    - pytest
    - matplotlib-base

about:
  home: http://speclite.readthedocs.io/en/latest/overview.html
  license: BSD-3-Clause
  license_family: BSD
  summary: This package provides a set of lightweight utilities for working with spectroscopic data in astronomy. Based on the astropy affiliated package template.
  license_file: licenses/LICENSE.rst
  dev_url: https://github.com/dkirkby/speclite
  doc_url: http://speclite.readthedocs.io/en/latest/overview.html

extra:
  recipe-maintainers:
    - giacomov
    - dkirkby
