travis:
  secure:
    BINSTAR_TOKEN: vbAfHFIGvKe3MHk/jtHAy52snFY22RM2gDMDVEfPH2QY/qyGWnhfWsZawNwnTVdGjWQ9oRgTg8MLgnLBALqI244VCI6vx6jve1kLm1xV/8Jhz1TjzHMr4Ou9njs8JOqud/F+GHfLy8lUeIn+A9EhayjOnzaMx5hkHaiT8KZCJA+GwwRL6XzvMiP42uBWq2q7wbnqrfr92G9L6IH+cKVoIHBDGjSmMtekvvEuN7ZKwTiqn/TcdENGq/fVLKPyTTK0cXhoeIGHmmeR5LnRo1ZysWRVelY5t4YO0uoacOMBGfbAHGk7+YsYF7PeAm3u9Ooa/YL8+Bmwiuy5Qs15qrwd+/mPgRZ3BCWcc82kpVXgLkUVWzx/EOgRJZ/eHO8EFFnGJN5lqIJvbM4uiZLozKX1U7L3ds/b0rPnyvRtjAvLCZvYKY8MCIP4DgeyEAite0i2Sb3UD+6TqXPmI7epqCPSgx5ywxGym1xLmva94LaVdjZ+KDnI64brIdpfQiAHDY5tQ68gd2gWpU7NBEAzGvE8ARwyWZ5v40gX5ZRM4wIihnHMzDh+uPfuKgbo2OteyKUo9eYPyehZPt2IyxeayNXRLPMLE3/FF0eRw92phTtHpV4n7Fg37qwhH75NFLauY3qjcMJZVJgUTtdiaxtdXx1zqeSCQC25xjbVtAdmhxMed8o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
