travis:
  secure:
    BINSTAR_TOKEN: LSNW3mokDThtm4V2OJnOds7kqOxKIB4zPd6yIhQ99tqRNr0D5RvYxdMis6Nb61WvBJZl4PmcKbSproBJG+KwJ154zAUTjWcv0iLQCkZ1IBXP+MfR4l3EEGYdNkGfr0hEsJjfX55HFO5vqnkB3Vu+Z3xj0aFXL9Pn1Y7Vz6k6wFQxDebxUEeIsFQiIYKOR0OpJ7ADEmR2L152wF0qqlbUd5+MxK4pWUIxziP8QOBT9MGvAjTpYd2Kx8xTv3lqR6zt3+zvAyOsNMHtMdnu89lF999F1x1YuxQyT4cNbInKhxADfq64ymMWmExC9GSdBWFMOdODPM/c+UIVB5fa3O/5qBqSIjMdXTgenTu2HCkOP+D35bYsnR6rzOh5fAnpXITJI1tvpqouUdu4qyIHAzVQxEmDtUI7Jp/8Jnnip7QqE+r5MaWe1+R4EFwXrryKiOvu3/RahBHpegASIxjrB2vud+a2X2GmikfEk9RoYiSYeeB7FKnVSAEI4zMldT9qagBzSaQR1ZkFRFNXpdYXI6ceogAsRtEXz6VhKPvbyhP6Oo2qtzeTSisuKlx1ELffiKeOVAVU10DqBUq+523u9z4DgwtTTmL7XEt9pbzjqXjDNPbILMeBDXEWlnDaoEMpTqO1BcIXAPA77OpOXYnOphjhCXBUh1wB5Ulys2j/BQoK0UQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
